springdoc:
  api-docs:
    path: /swagger/api-docs


publisher:
  context:
    path: /publisher
  stats: /stats


# ActiveMQ properties.
spring:
  activemq:
    broker-url: tcp://localhost:61616
    jms:
      pub-sub-domain: true
    packages:
      trusted: com.broker.activemq.entities, java.lang
    in-memory: true
    close-timeout: 15
    password: admin
    user: admin
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
